# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
#events
on:
  #event 1
  push:
    branches: [ "main" ]
    #event 2
  pull_request:
    branches: [ "main" ]

jobs:
  #First job
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: "Install dependencies"
      run: npm install
    - name: "Run Build command"
    - run: echo "npm run build -> Building the source code"
    - name: "Build successful"
      run: echo "Build completed successfully"

      
  # Second job
  Test:
   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: "Install dependencies"
      run: npm install
    
    - name: "Testing command"
      run: echo "npm test -> Running tests"

    - name: "Testing successful"
      run: echo "App tested successfully"
    - name: "All tests passed"
      run: echo "All tests have passed successfully"

    
